/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: brianj.seely (https://sketchfab.com/brianj.seely)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/digestive-system-2412d3f9bf17412db96b0718931a4efe
Title: Digestive System
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const DigestiveSystem = (props) => {
  const { nodes, materials } = useGLTF("/models/digestive_system.glb");
  return (
    <group {...props} dispose={null} scale={3.5} position={[0, -3.5, 0]}>
      <group rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.StingrayPBS1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.StingrayPBS5}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9.geometry}
        material={materials.StingrayPBS3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.StingrayPBS4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_11.geometry}
        material={materials.StingrayPBS2}
      />
    </group>
  );
};

useGLTF.preload("/models/digestive_system.glb");

export default DigestiveSystem;
